name: 'hicks_landscaping_analytics'
version: '1.0.0'
config-version: 2

profile: 'hicks_landscaping_analytics'

model-paths: ["models"]
seed-paths: ["data/raw"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hicks_landscaping_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
